# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: my-service-name
  tag: stable
  pullPolicy: Never
  secrets:
    - name: gitlab-registry
application:
  track: stable
  tier: web
service:
  enabled: true
  name: web
  type: ClusterIP
  url: http://my.host.com/
  externalPort: 80
  internalPort: 80
postgresql:
  # There's old postgress code from GitLab's chart defn in here
  enabled: false
resources:
#  limits:
#    cpu: 100m
#    memory: 128Mi
#  requests:
#    cpu: 100m
#    memory: 128Mi
